### ISSUE TITLE
`hex_string` should not return Result, it should just return String

### ISSUE THREAD

**Issue by nakedible-p** [nervosnetwork/faster-hex#16]
Currently `hex_string` is `pub fn hex_string(src: &[u8]) -> Result<String, Error>`. However, the only `Error` possible is `InvalidLength` which happens when `hex_encode` destination buffer length is wrong. However, `hex_string` is allocating the buffer itself, so the length is never wrong, hence `hex_string` can only panic and the return type should just be `String`.

**Comment by zhangsoledad** [comment]
https://github.com/nervosnetwork/faster-hex/releases/tag/v0.6.0
