### ISSUE TITLE
serde support 

### ISSUE THREAD

**Issue by zhangsoledad** [nervosnetwork/faster-hex#25]
Some design is needed,
to be as generic as possible while still meeting existing requirements https://github.com/nervosnetwork/ckb/blob/develop/util/jsonrpc-types/src/bytes.rs.
Support configuration 0x-prefix, case-sensitive, bytes/Vec<u8>, etc.

**Comment by eval-exec** [comment]
* proposal

Inspired by [serde-hex](https://github.com/fspmarshall/serde-hex/blob/master/src/lib.rs), I want to make faster-hex cooperate with serde in such usages:

```rust
// will get 0x prefixed, lower case hex string, like: "0x01020a0b"
struct Foo {
  #[serde(with = "faster_hex")]
  bar: Vec<u8>
}
```

```rust
// will get no 0x prefixed, lower case hex string, like: "01020a0b"
struct Foo {
  #[serde(with = "faster_hex::SerHex::<NoPfxNoCap>")]
  bar: Vec<u8>
}
```
```rust
// will get no 0x prefixed, upper case hex string, like: "01020A0B"
struct Foo {
  #[serde(with = "faster_hex::SerHex::<NoPfxWithCap>")]
  bar: Vec<u8>
}
```
```rust
// will 0x prefixed, upper case hex string, like: "0x01020A0B"
struct Foo {
  #[serde(with = "faster_hex::SerHex::<WithPfxWithCap>")]
  bar: Vec<u8>
}
```



I want add two features to : `serde` and `serde_bytes`

## feature `serde`
This feature allow serde to de/serialize `Vec<u8>` field.

## feature `serde_bytes`
This feature will depend on `bytes` crate, and allow serde to de/serialize `Bytes` field.

**Comment by SuperFluffy** [comment]
Found this feature and wanted to use it, but it's not yet released crates.io. :( Do you have plans to cut a new release?

**Comment by eval-exec** [comment]
@SuperFluffy Yes, future release planned.
