### ISSUE TITLE
Fails to build on x86 without SSE2

### ISSUE THREAD

**Issue by jbeich** [nervosnetwork/faster-hex#32]
FreeBSD, NetBSD, OpenBSD still support pre-SSE2 CPUs, so downstream `rust` package for 32-bit x86 (aka i386) targets real i686 (aka `pentiumpro`) or i586 (aka `pentium`). To reproduce on Linux (via rustup) pass `--target i586-unknown-linux-gnu` or similar.

```rust
$ cargo build
[...]
error[E0425]: cannot find function `vectorization_support_no_cache_x86` in this scope
  --> src/lib.rs:63:28
   |
63 |         let val = unsafe { vectorization_support_no_cache_x86() };
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `faster-hex` (lib) due to previous error
```

**Comment by kekePower** [comment]
I see the same thing on Mageia Cauldron i586.
Log: https://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20230828191443.kekepower.duvel.1005060/cargo-c-0.9.24-1.mga10/build.i586.0.20230828191507.log
