### ISSUE TITLE
Release 0.8.2 broke cargo-audit

### ISSUE THREAD

**Issue by SZenglein** [nervosnetwork/faster-hex#43]
Due to the 0.8.2 relase of faster-hex, gix-hash and by extension cargo audit breaks. 

I can no longer install cargo-audit. I suspect this is breaking a few other CIs as well.

I'm not sure, but 0.8.2 was a breaking change and should have been 0.9?

**Comment by eval-exec** [comment]
How did you install cargo-audit?

**Comment by SZenglein** [comment]
cargo install cargo-audit

**Comment by ciffelia** [comment]
I think commit 160ef4dae676fe0619a3ac559f1a6f7ecd5d4f3e has a problem. Adding new enum variants is a breaking change.

https://doc.rust-lang.org/cargo/reference/semver.html#enum-variant-new

**Comment by SZenglein** [comment]
> I think commit [160ef4d](https://github.com/nervosnetwork/faster-hex/commit/160ef4dae676fe0619a3ac559f1a6f7ecd5d4f3e) has a problem. Adding new enum variants is a breaking change.
> 
> https://doc.rust-lang.org/cargo/reference/semver.html#enum-variant-new

Definitely the error thrown when compiling is due to a non-exhaustive match

**Comment by marcbrevoort-cyberhive** [comment]
Broken here too.
```
`faster_hex::Error::Overflow` not covered
   --> /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gix-hash-0.13.1/src/prefix.rs:117:28
    |
117 |         .map_err(|e| match e {
    |                            ^ pattern `faster_hex::Error::Overflow` not covered
    |
note: `faster_hex::Error` defined here
   --> /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/faster-hex-0.8.2/src/error.rs:5:5
    |
2   | pub enum Error {
    | --------------
...
5   |     Overflow,
    |     ^^^^^^^^ not covered
    = note: the matched value is of type `faster_hex::Error`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
    |
119 ~             faster_hex::Error::InvalidLength(_) => panic!("This is already checked"),
120 ~             faster_hex::Error::Overflow => todo!(),
    |
```

**Comment by eval-exec** [comment]
Going to yank v0.8.2.

**Comment by eval-exec** [comment]
`faster-hex@0.8.2` was yanked now.

**Comment by machta** [comment]
I recommend using the [`--locked` option](https://doc.rust-lang.org/cargo/commands/cargo-install.html#dealing-with-the-lockfile). This makes cargo respect Cargo.lock files from the packages and not select the newest possible version.

```
cargo install --locked cargo-audit
```

For us it fixed the issue in our build pipeline.

**Comment by SZenglein** [comment]
That does not help if running from inside a fresh container.

Anyway, thanks @eval-exec for fixing the release!
